export const product = [
  {
    id: 1,
    title: "The Complete Python Bootcamp From Zero to Hero in Python",
    description:
      "A practical programming course for office workers, academics, and administrators who want to improve their productivity.",
    price: 549,
    discountPercentage: 12.96,
    rating: 4.69,
    stock: 94,
    brand: "Apple",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
    images: ["/Product/1.jpg"],
  },
  {
    id: 2,
    title: "Automate Programming",
    description:
      "Learn to style and add animations to bring those basic web pages to life using CSS to bring those basic web pages",
    price: 899,
    discountPercentage: 17.94,
    rating: 4.44,
    stock: 34,
    brand: "Apple",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
    images: ["/Product/2.jpg"],
  },
  {
    id: 3,
    title: "ChatGPT Prize [2024]",
    description:
      "Learn to create Machine Learning Algorithms in Python and R from two Data Science experts. Code templates included.",
    price: 1249,
    discountPercentage: 15.46,
    rating: 4.09,
    stock: 36,
    brand: "Samsung",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/3/thumbnail.jpg",
    images: ["/Product/3.jpg"],
  },
  {
    id: 4,
    title: "Python : Master Programming",
    description:
      "Learn complete Python with Basics, Data Science, Data Visualisation, Desktop Graphical Applications and Machine Learning",
    price: 280,
    discountPercentage: 17.91,
    rating: 4.3,
    stock: 123,
    brand: "OPPO",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
    images: ["/Product/4.jpg"],
  },
  {
    id: 5,
    title: "Ultimate AWS Certified Cloud",
    description:
      "Full Practice Exam included + explanations | Learn Cloud Computing | Pass the AWS Cloud Practitioner CLF-C02 exam!",
    price: 499,
    discountPercentage: 10.58,
    rating: 4.09,
    stock: 32,
    brand: "Huawei",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/5/thumbnail.jpg",
    images: ["/Product/5.jpg"],
  },
  {
    id: 6,
    title: "The Complete JavaScript Course 2024",
    description:
      "The modern JavaScript course for everyone! Master JavaScript with projects, challenges and theory. Many courses in one!",
    price: 1749,
    discountPercentage: 11.02,
    rating: 4.57,
    stock: 83,
    brand: "Apple",
    category: "laptops",
    thumbnail: "https://i.dummyjson.com/data/products/6/thumbnail.png",
    images: ["/Product/6.jpg"],
  },
  {
    id: 7,
    title: "Microsoft Excel",
    description:
      "Excel with this A-Z Microsoft Excel Course. Microsoft Excel 2010, 2013, 2016, Excel 2019 and Microsoft/Office 365/2023",
    price: 1499,
    discountPercentage: 4.15,
    rating: 4.25,
    stock: 50,
    brand: "Samsung",
    category: "laptops",
    thumbnail: "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
    images: ["/Product/7.jpg"],
  },
  {
    id: 8,
    title: "The Data Science Course",
    description:
      "Complete Data Science Training: Mathematics, Statistics, Python, Advanced Statistics in Python, Machine &amp; Deep Learning",
    price: 1499,
    discountPercentage: 10.23,
    rating: 4.43,
    stock: 68,
    brand: "Microsoft Surface",
    category: "laptops",
    thumbnail: "https://i.dummyjson.com/data/products/8/thumbnail.jpg",
    images: ["/Product/8.jpg"],
  },
  {
    id: 9,
    title: "Ultimate AWS Certified ",
    description:
      "Full Practice Exam included + explanations | Learn Cloud Computing | Pass the AWS Cloud Practitioner CLF-C02 exam!",
    price: 1099,
    discountPercentage: 11.83,
    rating: 4.54,
    stock: 96,
    brand: "Infinix",
    category: "laptops",
    thumbnail: "https://i.dummyjson.com/data/products/9/thumbnail.jpg",
    images: ["/Product/9.jpg"],
  },
  {
    id: 10,
    title: "The Complete 2024 Web Development Bootcamp",
    description:
      "Become a Full-Stack Web Developer with just ONE course. HTML, CSS, Javascript, Node, React, PostgreSQL, Web3 and DApps",
    price: 1099,
    discountPercentage: 6.18,
    rating: 4.43,
    stock: 89,
    brand: "HP Pavilion",
    category: "laptops",
    thumbnail: "https://i.dummyjson.com/data/products/10/thumbnail.jpeg",
    images: ["/Product/10.jpg"],
  },
];
